- name: executing remote ssh commands using ssh key
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USER }}
    key: ${{ secrets.KEY }}
    port: ${{ secrets.PORT }}
    script: whoami
